levels:
  - A1
  - A2
  - B1
  - B2
  - C1
  - C2
  - Native

# Pre-defined 100 most commonly spoken languages in the world + a couple others
languages:
  - Akan
  - Amharic
  - Arabic
  - Assamese
  - Awadhi
  - Azerbaijani
  - Balochi
  - Belarusian
  - Bengali
  - Bhojpuri
  - Burmese
  - Cantonese
  - Cebuano
  - Chewa
  - Chhattisgarhi
  - Chittagonian
  - Czech
  - Deccan
  - Dhundhari
  - Dutch
  - Eastern Min
  - English
  - Esperanto
  - French
  - Fula
  - Fuzhounese
  - Gan
  - German
  - Greek
  - Gujarati
  - Haitian Creole
  - Hakka
  - Haryanvi
  - Hausa
  - Hiligaynon
  - Hindi
  - Hmong
  - Hokkien
  - Hungarian
  - Hunnanese
  - Ido
  - Igbo
  - Ilocano
  - Ilonggo
  - Indonesian
  - Interlingua
  - Italian
  - Japanese
  - Javanese
  - Jin
  - Kannada
  - Kazakh
  - Khmer
  - Kinyarwanda
  - Kirundi
  - Konkani
  - Korean
  - Kurdish
  - Lao
  - Latin
  - Madurese
  - Magahi
  - Maithili
  - Malagasy
  - Malay
  - Malayalam
  - Malaysian
  - Mandarin
  - Marathi
  - Marwari
  - Mossi
  - Nepali
  - Northern Min
  - Odia
  - Oriya
  - Oromo
  - Pashto
  - Persian
  - Polish
  - Portuguese
  - Punjabi
  - Quechua
  - Romanian
  - Russian
  - Saraiki
  - Serbo-Croatian
  - Shanghainese
  - Shona
  - Sindhi
  - Sinhalese
  - Somali
  - Southern Min
  - Spanish
  - Sundanese
  - Swedish
  - Sylheti
  - Tagalog
  - Tamil
  - Telugu
  - Teochew
  - Thai
  - Turkish
  - Turkmen
  - Ukrainian
  - Urdu
  - Uyghur
  - Uzbek
  - Vietnamese
  - Wu
  - Xhosa
  - Xiang
  - Yoruba
  - Yue
  - Zhuang
  - Zulu