name: LLChat
main: me.cxom.llchat.LLChat
version: 2.7
description: A custom chat plugin for the AroundTheWorldMC /r/languagelearning server

commands:
  lltest:
  lltest2:
  channel:
    aliases: [ch, chat]
    